
name: Rust

on: [push]

jobs:
  ci:
    runs-on: windows-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.34.0  # MSRV

    steps:
    - uses: actions/checkout@v2

    - name: Cargo "test" (which builds the examples)
      run: cargo test
